import type { CallToolResult, JSONSchema } from "../../types/content"
import type { ToolWireDefinition } from "../../types/driver"
import type { Icon, ToolAnnotations } from "../../types/tool"

/**
 * Payload provided to a tool's execute() function.
 */
export interface ToolInvocation<P = unknown> {
	/** Unique tool call identifier. */
	callId: string

	/** Name of the tool being executed. */
	toolName: string

	/** Validated arguments passed to the tool. */
	params: P

	/** Optional abort signal from the active turn. */
	signal?: AbortSignal

	/** Optional active session identifier. */
	sessionId?: string

	/** Callback for streaming progress updates. */
	progress?: (update: string | unknown) => void
}

/**
 * Tool executor return types: structured CallToolResult, string, or void.
 */
// biome-ignore lint/suspicious/noConfusingVoidType: Tool executors can return void or undefined when producing no output.
export type ToolExecuteResult = CallToolResult | string | undefined | void

/**
 * Execution function implemented by a tool.
 */
export type ToolExecute<P = unknown> = (
	invocation: ToolInvocation<P>,
) => Promise<ToolExecuteResult> | ToolExecuteResult

/**
 * Standard tool definition stored in the tools registry.
 */
export interface ToolDefinition<P = unknown> {
	/** Tool name identifier (1-128 chars). */
	name: string

	/** Human-readable description presented to models. */
	description: string

	/** JSON-Schema (2020-12) describing the input parameters. */
	inputSchema: JSONSchema

	/** Local executor function. */
	execute: ToolExecute<P>

	/** Optional human-friendly title. */
	title?: string

	/** JSON-Schema describing output structure. */
	outputSchema?: JSONSchema

	/** Optional categorization tags for availability filtering. */
	tags?: string[]

	/** Optional display icon assets. */
	icons?: Icon[]

	/** Optional execution hints (read-only, destructive, idempotent). */
	annotations?: ToolAnnotations

	/** When true, marks tool for serialized non-parallel execution. */
	serial?: boolean
}

/**
 * Filter criteria for listing available tools.
 */
export interface ToolFilter {
	/** Allow-list of tool names. */
	allow?: string[]

	/** Deny-list of tool names. */
	deny?: string[]

	/** Require at least one matching tag. */
	tags?: string[]

	/** Exclude tools having any of these tags. */
	excludeTags?: string[]
}

/**
 * Payload transformed by the 'tool/pre-execute' waterfall.
 */
export interface ToolPreExecutePayload {
	/** Unique tool call ID. */
	callId: string

	/** Target tool name. */
	toolName: string

	/** Parsed parameter arguments. */
	params: Record<string, unknown>

	/** When set to true by middleware, blocks tool execution. */
	block?: boolean

	/** Rejection or blocking rationale. */
	reason?: string
}

/**
 * Context provided to 'tool/pre-execute' waterfall handlers.
 */
export interface ToolPreExecuteContext {
	callId: string
	toolName: string
	sessionId?: string
}

/**
 * Context provided to 'tool/post-execute' waterfall handlers.
 */
export interface ToolPostExecuteContext {
	callId: string
	toolName: string
	sessionId?: string
	params: Record<string, unknown>
}

/**
 * Parameters for invoking a tool through ctx.tools.execute().
 */
export interface ToolExecuteCall {
	/** Unique call ID generated by the model. */
	callId: string

	/** Target tool name. */
	toolName: string

	/** Input arguments as an object or raw JSON string. */
	arguments: unknown

	/** Optional active session ID. */
	sessionId?: string

	/** Optional abort signal. */
	signal?: AbortSignal

	/** Optional progress update callback. */
	progress?: (update: string | unknown) => void
}

/**
 * Service managing tool registration, wire projection, and waterfall execution.
 */
export interface ToolService {
	/**
	 * Registers a tool into the service. Returns a dispose function that restores any shadowed tool.
	 * @param tool Tool definition.
	 */
	register(tool: ToolDefinition): () => void

	/**
	 * Retrieves a registered tool definition by name.
	 * @param name Tool name.
	 */
	get(name: string): ToolDefinition | undefined

	/**
	 * Checks if a tool with the specified name is currently registered.
	 * @param name Tool name.
	 */
	has(name: string): boolean

	/**
	 * Lists registered tools optionally filtered by name or tags.
	 * @param filter Optional filter criteria.
	 */
	list(filter?: ToolFilter): ToolDefinition[]

	/**
	 * Projects registered tools into minimal wire definitions sent to drivers.
	 * @param filter Optional filter criteria.
	 */
	projectWireTools(filter?: ToolFilter): ToolWireDefinition[]

	/**
	 * Executes a tool through the pre-execute waterfall, schema validation, and post-execute waterfall.
	 * @param call Tool execution parameters.
	 */
	execute(call: ToolExecuteCall): Promise<CallToolResult>
}

declare module "../kernel/types" {
	interface HarnessServices {
		tools?: ToolService
	}
}
